apiVersion: v1
# used to attach to pod config
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec: 
  accessModes:
    - ReadWriteOnce
  resources:
    requests: 
      storage: 2Gi